services:
  grafana:
    image: 'grafana/grafana:latest'
    container_name: tha_grafana
    environment:
      GF_SECURITY_ADMIN_USER: '${GF_SECURITY_ADMIN_USER}'
      GF_SECURITY_ADMIN_PASSWORD: '${GF_SECURITY_ADMIN_PASSWORD}'
      GF_SERVER_DOMAIN: 'analytics.thehockeyanalytics.com'
      GF_SERVER_ROOT_URL: 'https://analytics.thehockeyanalytics.com'
      GF_INSTALL_PLUGINS: 'grafana-clickhouse-datasource'
      GF_FEATURE_TOGGLES_ENABLE: 'publicDashboards'
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_SECURITY_COOKIE_SAMESITE: 'lax'
      GF_AUTH_DISABLE_LOGIN_FORM: 'false'
      GF_AUTH_DISABLE_SIGNOUT_MENU: 'false'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_USERS_ALLOW_ORG_CREATE: 'false'
      GF_USERS_AUTO_ASSIGN_ORG: 'true'
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: 'Viewer'
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - 'grafana_provisioning:/etc/grafana/provisioning'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`analytics.thehockeyanalytics.com`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.service=grafana"
    restart: unless-stopped
    networks:
      - coolify

volumes:
  grafana_data:
    driver: local
  grafana_provisioning:
    driver: local

networks:
  coolify:
    external: true
