services:
  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: tha_minio
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=https://data.thehockeyanalytics.com
      - MINIO_BROWSER_REDIRECT_URL=https://data.thehockeyanalytics.com
    volumes:
      - 'minio_data:/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`data.thehockeyanalytics.com`)"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.service=minio"
    restart: unless-stopped
    networks:
      - coolify

volumes:
  minio_data:
    driver: local

networks:
  coolify:
    external: true